# SimpleMobControl Plugin by xKev
# Version 0.1
# Write all the mob names you want to disable in here.
# Syntax:    - Mobname       (4 (four) spaces in front of the -)
Disabled Mobs:
    - Creeper
    - Spider
    - Sheep