name: SimpleMobControl
author: xKev
version: 0.6
description: A simple Plugin which is used to enable/disable all kind of mobs in Minecraft.

main: com.xkev.SimpleMobControl.SimpleMobControl

commands:
  simpleMobControl:
    description: All Simple Mob Control Commands
    aliases: smc
    usage: "Usage: /simplemobcontrol "


permissions:
  simplemobcontrol.*:
    description: Gives acces to all SimpleMobControl commands.
    default: op
    children:
      simplemobcontrol.configure: true
      simplemobcontrol.info: true
  simplemobcontrol.info:
    description: Allows you to see all currently disabled mobs.
    default: true
  simplemobcontrol.configure:
    description: Allows you to configure the currently disabled mobs.
    children:
      simplemobcontrol.info: true
