name: SimpleMobControl
author: xKev
version: 0.4
description: A simple Plugin which is used to enable/disable all kind of mobs in Minecraft.

main: com.xkev.SimpleMobControl.Main

commands:
  disableMob:
    description: Disables a specific mob.
    permission: simplemobcontrol.configure
    usage: "Usage: /disablemob <mobname> or <all>"
  showAvailableMobs:
    description: Shows all mobs available.
    permission: simplemobcontrol.configure
    usage: "Usage: /showavailablemobs"
  showDisabledMobs:
    description: Shows all disabled mobs.
    permission: simplemobcontrol.info
    usage: "Usage: /showdisabledmobs"
  enableMob:
    description: Enables a specific mob.
    permission: simplemobcontrol.configure
    usage: "Usage: /enablemob <mobname> or <all> "

permissions:
  simplemobcontrol.*:
    description: Gives acces to all SimpleMobControl commands.
    default: op
    children:
      simplemobcontrol.configure: true
      simplemobcontrol.info: true
  simplemobcontrol.info:
    description: Allows you to see all currently disabled mobs.
    default: true
  simplemobcontrol.configure:
    description: Allows you to configure the currently disabled mobs.
    children:
      simplemobcontrol.info: true
