# SimpleMobControl Plugin by xKev
# Version 0.1
# Write all the mob names you want to disable in here.
# This list can be configured ingame with the command /disablemob <mob>
# Syntax: - Mobname
Disabled Mobs:
- Creeper
- Spider
- Sheep